-- Car Rental API schema. Paste into Supabase SQL Editor and run.

create extension if not exists btree_gist with schema extensions;

-- Tables

create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  name       text not null,
  email      text not null unique,
  role       text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id               bigint generated by default as identity primary key,
  brand            text not null,
  model            text not null,
  year             int not null check (year between 1990 and 2100),
  category         text not null check (category in ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
  daily_rate       numeric(10, 2) not null check (daily_rate > 0),
  fuel_type        text not null,
  seating_capacity int not null default 5 check (seating_capacity between 1 and 15),
  status           text not null default 'available' check (status in ('available', 'rented', 'maintenance')),
  created_at       timestamptz not null default now()
);

create table if not exists public.rentals (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users (id) on delete restrict,
  vehicle_id     bigint not null references public.vehicles (id) on delete restrict,
  customer_name  text not null,
  customer_email text not null,
  start_date     date not null,
  end_date       date not null,
  total_cost     numeric(10, 2) not null check (total_cost > 0),
  status         text not null default 'booked' check (status in ('booked', 'active', 'completed', 'cancelled')),
  created_at     timestamptz not null default now(),
  constraint valid_date_range check (end_date >= start_date),
  constraint no_double_booking exclude using gist (
    vehicle_id with =,
    daterange(start_date, end_date, '[]') with &&
  ) where (status in ('booked', 'active'))
);

create index if not exists rentals_user_id_idx on public.rentals (user_id);
create index if not exists rentals_vehicle_id_idx on public.rentals (vehicle_id);
create index if not exists vehicles_category_status_idx on public.vehicles (category, status);

-- Functions

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql stable
security definer set search_path = ''
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.vehicle_schedule(p_vehicle_id bigint)
returns table (id bigint, start_date date, end_date date, status text)
language sql stable
security definer set search_path = ''
as $$
  select r.id, r.start_date, r.end_date, r.status
  from public.rentals r
  where r.vehicle_id = p_vehicle_id
  order by r.start_date desc;
$$;

create or replace function public.busy_vehicle_ids(p_start date, p_end date)
returns setof bigint
language sql stable
security definer set search_path = ''
as $$
  select distinct r.vehicle_id
  from public.rentals r
  where r.status in ('booked', 'active')
    and r.start_date <= p_end
    and r.end_date >= p_start;
$$;

create or replace function public.guard_rental_write()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  rate numeric;
begin
  if tg_op = 'INSERT' then
    select daily_rate into rate from public.vehicles where id = new.vehicle_id;
    if rate is not null and new.total_cost <> rate * (new.end_date - new.start_date + 1) then
      raise exception 'total_cost does not match the vehicle daily rate' using errcode = 'P0001';
    end if;
    return new;
  end if;

  if public.is_admin() then
    return new;
  end if;

  if old.status <> 'booked'
     or new.status <> 'cancelled'
     or (to_jsonb(new) - 'status') <> (to_jsonb(old) - 'status') then
    raise exception 'customers can only cancel their own booked rentals' using errcode = '42501';
  end if;
  return new;
end;
$$;

grant execute on function public.vehicle_schedule(bigint) to anon, authenticated;
grant execute on function public.busy_vehicle_ids(date, date) to anon, authenticated;

-- Triggers

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace trigger rentals_guard
  before insert or update on public.rentals
  for each row execute function public.guard_rental_write();

-- Row level security

alter table public.profiles enable row level security;
alter table public.vehicles enable row level security;
alter table public.rentals  enable row level security;

drop policy if exists "own profile or admin" on public.profiles;
create policy "own profile or admin" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists "anyone can view vehicles" on public.vehicles;
create policy "anyone can view vehicles" on public.vehicles
  for select to anon, authenticated
  using (true);

drop policy if exists "admins add vehicles" on public.vehicles;
create policy "admins add vehicles" on public.vehicles
  for insert to authenticated
  with check (public.is_admin());

drop policy if exists "admins update vehicles" on public.vehicles;
create policy "admins update vehicles" on public.vehicles
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "admins delete vehicles" on public.vehicles;
create policy "admins delete vehicles" on public.vehicles
  for delete to authenticated
  using (public.is_admin());

drop policy if exists "own rentals or admin" on public.rentals;
create policy "own rentals or admin" on public.rentals
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists "book for yourself" on public.rentals;
create policy "book for yourself" on public.rentals
  for insert to authenticated
  with check (user_id = auth.uid() and status = 'booked');

drop policy if exists "update own rentals or admin" on public.rentals;
create policy "update own rentals or admin" on public.rentals
  for update to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

-- After registering the admin account, run:
-- update public.profiles set role = 'admin' where email = 'admin@travel.com';
